// AUTO-GENERATED by scripts/foodi/download_foodi_images.py
// Source: FooDI-ML dataset (Glovo) — AR products
// imageStatus "needs_review" — manual review required before production use
//
// To approve a product: change status → "approved" and imageStatus → "approved"
// To reject:            change status → "rejected"
//
// Seed Firestore: open /admin/catalogo → click "Importar FooDI-ML"

import type { FoodiSeedProduct } from '@/lib/types'

export const foodiArProducts: FoodiSeedProduct[] = [
  {
    "id": "foodi-ar-toalla-fem-always-basica-seca-8u",
    "name": "Toalla Fem Always Basica Seca 8U",
    "normalizedName": "toalla fem always basica seca 8u",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "toalla fem always basica seca 8u"
    ],
    "imageUrl": "/products/foodi-ar/toalla-fem-always-basica-seca-8u.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_004",
      "s3Path": "dataset/RSDQDRN_0015836_1181880507.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-cerveza-artesanal-maddok-rocoto-botella-330ml",
    "name": "Cerveza Artesanal MADDOK Rocoto Botella 330ml",
    "normalizedName": "cerveza artesanal maddok rocoto botella 330ml",
    "brand": "",
    "categoryId": "bebidas",
    "unit": "330ml",
    "aliases": [
      "cerveza artesanal maddok rocoto botella 330ml",
      "cerveza artesanal maddok rocoto botella"
    ],
    "imageUrl": "/products/foodi-ar/cerveza-artesanal-maddok-rocoto-botella-330ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_009",
      "s3Path": "dataset/HLKTVWG_0005942_710279562.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-atun-sardimar-light-chile-jalapeno-140-gr",
    "name": "Atun Sardimar Light Chile Jalapeño 140 Gr",
    "normalizedName": "atun sardimar light chile jalapeno 140g",
    "brand": "",
    "categoryId": "otros",
    "unit": "140 gr",
    "aliases": [
      "atun sardimar light chile jalapeno 140g",
      "atun sardimar light chile jalapeno"
    ],
    "imageUrl": "/products/foodi-ar/atun-sardimar-light-chile-jalapeno-140-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_015",
      "s3Path": "dataset/RSDQDRN_0006739_996272238.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-kit-cabello-post-alisado-kerastimask-placenta-life-be-natural-1-ud",
    "name": "Kit Cabello Post Alisado Kerastimask Placenta Life Be Natural 1 Ud.",
    "normalizedName": "kit cabello post alisado kerastimask placenta life be natural 1 ud",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "kit cabello post alisado kerastimask placenta life be natural 1 ud"
    ],
    "imageUrl": "/products/foodi-ar/kit-cabello-post-alisado-kerastimask-placenta-life-be-natural-1-ud.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_016",
      "s3Path": "dataset/CBNGZLF_0042555_1511828574.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-galak-sanduche-87-gr",
    "name": "Galak Sanduche 87 Gr",
    "normalizedName": "galak sanduche 87g",
    "brand": "",
    "categoryId": "otros",
    "unit": "87 gr",
    "aliases": [
      "galak sanduche 87g",
      "galak sanduche"
    ],
    "imageUrl": "/products/foodi-ar/galak-sanduche-87-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "57380 (BOE)",
      "s3Path": "dataset/DDLRZFC_0007610_1052851598.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-chuleta-de-pavita",
    "name": "Chuleta de Pavita",
    "normalizedName": "chuleta de pavita",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "chuleta de pavita"
    ],
    "imageUrl": "/products/foodi-ar/chuleta-de-pavita.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_009",
      "s3Path": "dataset/HLKTVWG_0006847_710283046.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-gran-dia-corn-flakes-510g",
    "name": "Gran Dia Corn Flakes 510g",
    "normalizedName": "gran dia corn flakes 510g",
    "brand": "",
    "categoryId": "almacen",
    "unit": "510g",
    "aliases": [
      "gran dia corn flakes 510g",
      "gran dia corn flakes"
    ],
    "imageUrl": "/products/foodi-ar/gran-dia-corn-flakes-510g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "PLR",
      "storeName": "AS_035",
      "s3Path": "dataset/RVSSQYC_0001724_1104913464.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-colonia-agua-fresca-de-azahara-aire-de-sevilla-150-ml",
    "name": "Colonia Agua Fresca De Azahara Aire De Sevilla 150 Ml.",
    "normalizedName": "colonia agua fresca de azahara aire de sevilla 150ml",
    "brand": "",
    "categoryId": "otros",
    "unit": "150 ml",
    "aliases": [
      "colonia agua fresca de azahara aire de sevilla 150ml",
      "colonia agua fresca de azahara aire de sevilla"
    ],
    "imageUrl": "/products/foodi-ar/colonia-agua-fresca-de-azahara-aire-de-sevilla-150-ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_016",
      "s3Path": "dataset/CBNGZLF_0043503_1511829677.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-pasta-fideos-knorr-caracoles-500-gr",
    "name": "Pasta Fideos Knorr Caracoles 500 Gr",
    "normalizedName": "pasta fideos knorr caracoles 500g",
    "brand": "",
    "categoryId": "otros",
    "unit": "500 gr",
    "aliases": [
      "pasta fideos knorr caracoles 500g",
      "pasta fideos knorr caracoles"
    ],
    "imageUrl": "/products/foodi-ar/pasta-fideos-knorr-caracoles-500-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "Walmart",
      "s3Path": "dataset/DDLRZFC_0002303_538937154.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-vegetal-15cm",
    "name": "Vegetal (15cm)",
    "normalizedName": "vegetal 15cm",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "vegetal 15cm"
    ],
    "imageUrl": "/products/foodi-ar/vegetal-15cm.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_043",
      "s3Path": "dataset/CBNGZLF_0007401_709963158.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-ob-medio-10un",
    "name": "Ob Medio 10Un",
    "normalizedName": "ob medio 10un",
    "brand": "",
    "categoryId": "otros",
    "unit": "10un",
    "aliases": [
      "ob medio 10un"
    ],
    "imageUrl": "/products/foodi-ar/ob-medio-10un.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "LMZ",
      "storeName": "Tienda Reciclaje",
      "s3Path": "dataset/HHZYWLV_0003374_1114574980.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-ades-jugo-soya-uva-200-ml",
    "name": "Ades Jugo Soya Uva 200 Ml",
    "normalizedName": "ades jugo soya uva 200ml",
    "brand": "",
    "categoryId": "otros",
    "unit": "200 ml",
    "aliases": [
      "ades jugo soya uva 200ml",
      "ades jugo soya uva"
    ],
    "imageUrl": "/products/foodi-ar/ades-jugo-soya-uva-200-ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0020091_1216629579.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-gaseosa-pepsi-black-botella-1-5l",
    "name": "Gaseosa PEPSI Black Botella 1.5L",
    "normalizedName": "gaseosa pepsi black botella 15l",
    "brand": "",
    "categoryId": "bebidas",
    "unit": "1.5l",
    "aliases": [
      "gaseosa pepsi black botella 15l",
      "gaseosa pepsi black botella"
    ],
    "imageUrl": "/products/foodi-ar/gaseosa-pepsi-black-botella-1-5l.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_015",
      "s3Path": "dataset/RSDQDRN_0002277_837177571.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-calabacita-kg",
    "name": "Calabacita Kg",
    "normalizedName": "calabacita kg",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "calabacita kg"
    ],
    "imageUrl": "/products/foodi-ar/calabacita-kg.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_053",
      "s3Path": "dataset/CBNGZLF_0033274_1177444524.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-cuchara-viva-bolsa-25-uns",
    "name": "Cuchara Viva Bolsa 25 Uns.",
    "normalizedName": "cuchara viva bolsa 25 uns",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "cuchara viva bolsa 25 uns"
    ],
    "imageUrl": "/products/foodi-ar/cuchara-viva-bolsa-25-uns.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0019718_1197780167.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-tinte-duo-colorcrem-kit-64ml-castano-claro-5",
    "name": "Tinte Duo Colorcrem Kit 64Ml Castano Claro 5",
    "normalizedName": "tinte duo colorcrem kit 64ml castano claro 5",
    "brand": "",
    "categoryId": "otros",
    "unit": "64ml",
    "aliases": [
      "tinte duo colorcrem kit 64ml castano claro 5",
      "tinte duo colorcrem kit castano claro 5"
    ],
    "imageUrl": "/products/foodi-ar/tinte-duo-colorcrem-kit-64ml-castano-claro-5.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_072",
      "s3Path": "dataset/HLKTVWG_0016819_1122756623.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-huggies-p-activsec-grande-44-unidades-1144",
    "name": "Huggies P Activsec Grande * 44 Unidades (1144)",
    "normalizedName": "huggies p activsec grande 44 unidades 1144",
    "brand": "",
    "categoryId": "otros",
    "unit": "44 unidades",
    "aliases": [
      "huggies p activsec grande 44 unidades 1144"
    ],
    "imageUrl": "/products/foodi-ar/huggies-p-activsec-grande-44-unidades-1144.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "PLR",
      "storeName": "AS_035",
      "s3Path": "dataset/RVSSQYC_0001910_1134628577.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-mp-collar-glitter-s-color-sujeto-a-disponibilidad-1-unidad-9397",
    "name": "Mp Collar Glitter S (Color Sujeto A Disponibilidad) 1 Unidad 9397",
    "normalizedName": "mp collar glitter s color sujeto a disponibilidad 1 unidad 9397",
    "brand": "",
    "categoryId": "mascotas",
    "unit": "nan",
    "aliases": [
      "mp collar glitter s color sujeto a disponibilidad 1 unidad 9397"
    ],
    "imageUrl": "/products/foodi-ar/mp-collar-glitter-s-color-sujeto-a-disponibilidad-1-unidad-9397.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0025398_1147133730.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-mopa-sintetica-great-value",
    "name": "Mopa Sintetica Great Value",
    "normalizedName": "mopa sintetica great value",
    "brand": "",
    "categoryId": "limpieza",
    "unit": "nan",
    "aliases": [
      "mopa sintetica great value"
    ],
    "imageUrl": "/products/foodi-ar/mopa-sintetica-great-value.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "Walmart",
      "s3Path": "dataset/DDLRZFC_0002183_538936782.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-gall-cachafaz-integral-avena-chips-225gr",
    "name": "Gall Cachafaz Integral Avena Chips 225Gr",
    "normalizedName": "gall cachafaz integral avena chips 225g",
    "brand": "",
    "categoryId": "snacks",
    "unit": "225gr",
    "aliases": [
      "gall cachafaz integral avena chips 225g",
      "gall cachafaz integral avena chips"
    ],
    "imageUrl": "/products/foodi-ar/gall-cachafaz-integral-avena-chips-225gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_072",
      "s3Path": "dataset/HLKTVWG_0016171_1107524808.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-mezcla-para-panqueques-maizena-165-g",
    "name": "Mezcla para Panqueques Maizena 165 g",
    "normalizedName": "mezcla para panqueques maizena 165g",
    "brand": "",
    "categoryId": "otros",
    "unit": "165 g",
    "aliases": [
      "mezcla para panqueques maizena 165g",
      "mezcla para panqueques maizena"
    ],
    "imageUrl": "/products/foodi-ar/mezcla-para-panqueques-maizena-165-g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_009",
      "s3Path": "dataset/HLKTVWG_0012042_945901138.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-aceite-gustadina-500-ml",
    "name": "Aceite Gustadina 500 Ml",
    "normalizedName": "aceite gustadina 500ml",
    "brand": "",
    "categoryId": "otros",
    "unit": "500 ml",
    "aliases": [
      "aceite gustadina 500ml",
      "aceite gustadina"
    ],
    "imageUrl": "/products/foodi-ar/aceite-gustadina-500-ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0011496_1144749497.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-untable-de-almendras-felices-las-vacas",
    "name": "Untable De Almendras - Felices Las Vacas",
    "normalizedName": "untable de almendras - felices las vacas",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "untable de almendras - felices las vacas"
    ],
    "imageUrl": "/products/foodi-ar/untable-de-almendras-felices-las-vacas.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Back up - Mercado Vívet ( BUE)",
      "s3Path": "dataset/CBNGZLF_0040995_1341212715.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-frijol-molido-negro-ducal-400g-doy-pack",
    "name": "Frijol Molido Negro Ducal 400G Doy Pack",
    "normalizedName": "frijol molido negro ducal 400g doy pack",
    "brand": "",
    "categoryId": "otros",
    "unit": "400g",
    "aliases": [
      "frijol molido negro ducal 400g doy pack",
      "frijol molido negro ducal doy pack"
    ],
    "imageUrl": "/products/foodi-ar/frijol-molido-negro-ducal-400g-doy-pack.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "QLM",
      "storeName": "AS_129",
      "s3Path": "dataset/BSCRBMV_0005405_1190563262.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-vizzio-nugaton-100-g-x-1",
    "name": "Vizzio nugaton 100 g. x 1",
    "normalizedName": "vizzio nugaton 100g x 1",
    "brand": "",
    "categoryId": "otros",
    "unit": "100 g",
    "aliases": [
      "vizzio nugaton 100g x 1",
      "vizzio nugaton x 1"
    ],
    "imageUrl": "/products/foodi-ar/vizzio-nugaton-100-g-x-1.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "ROS",
      "storeName": "Bonafide",
      "s3Path": "dataset/KLLRBTH_0002529_1122982434.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-sazonador-aji-no-moto-umami-glutamato-de-sodio-bolsa-100gr",
    "name": "Sazonador AJI-NO-MOTO Umami Glutamato de Sodio Bolsa 100Gr",
    "normalizedName": "sazonador aji-no-moto umami glutamato de sodio bolsa 100g",
    "brand": "",
    "categoryId": "almacen",
    "unit": "100gr",
    "aliases": [
      "sazonador aji-no-moto umami glutamato de sodio bolsa 100g",
      "sazonador aji-no-moto umami glutamato de sodio bolsa"
    ],
    "imageUrl": "/products/foodi-ar/sazonador-aji-no-moto-umami-glutamato-de-sodio-bolsa-100gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_015",
      "s3Path": "dataset/RSDQDRN_0002004_837172119.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-cama-afp-de-lana-para-perro-gris-s-1-unidad-3895",
    "name": "Cama Afp De Lana Para Perro Gris S 1 Unidad 3895",
    "normalizedName": "cama afp de lana para perro gris s 1 unidad 3895",
    "brand": "",
    "categoryId": "mascotas",
    "unit": "nan",
    "aliases": [
      "cama afp de lana para perro gris s 1 unidad 3895"
    ],
    "imageUrl": "/products/foodi-ar/cama-afp-de-lana-para-perro-gris-s-1-unidad-3895.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0025349_1147133680.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-brit-mono-protein-lamb-400-gr-69624",
    "name": "Brit Mono Protein Lamb 400 Gr (69624)",
    "normalizedName": "brit mono protein lamb 400g 69624",
    "brand": "",
    "categoryId": "otros",
    "unit": "400 gr",
    "aliases": [
      "brit mono protein lamb 400g 69624",
      "brit mono protein lamb 69624"
    ],
    "imageUrl": "/products/foodi-ar/brit-mono-protein-lamb-400-gr-69624.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_016",
      "s3Path": "dataset/CBNGZLF_0013129_1038144352.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-fideos-matarazzo-spaghetti-500gr",
    "name": "Fideos Matarazzo Spaghetti 500Gr",
    "normalizedName": "fideos matarazzo spaghetti 500g",
    "brand": "",
    "categoryId": "almacen",
    "unit": "500gr",
    "aliases": [
      "fideos matarazzo spaghetti 500g",
      "fideos matarazzo spaghetti"
    ],
    "imageUrl": "/products/foodi-ar/fideos-matarazzo-spaghetti-500gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_072",
      "s3Path": "dataset/HLKTVWG_0010515_896385481.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-jugo-dhoy-naranja-355cc",
    "name": "Jugo Dhoy Naranja 355Cc",
    "normalizedName": "jugo dhoy naranja 355cc",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "jugo dhoy naranja 355cc"
    ],
    "imageUrl": "/products/foodi-ar/jugo-dhoy-naranja-355cc.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "57380 (BOE)",
      "s3Path": "dataset/DDLRZFC_0007548_1052851049.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-lager-estrella-galicia-1-lt",
    "name": "Lager - Estrella Galicia (1 lt.)",
    "normalizedName": "lager - estrella galicia 1l",
    "brand": "",
    "categoryId": "bebidas",
    "unit": "1 lt",
    "aliases": [
      "lager - estrella galicia 1l",
      "lager - estrella galicia"
    ],
    "imageUrl": "/products/foodi-ar/lager-estrella-galicia-1-lt.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Cerveceria Untertürkheim",
      "s3Path": "dataset/CBNGZLF_0021597_1133247381.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-ginebra-tanqueray-dry-375ml",
    "name": "Ginebra Tanqueray Dry 375Ml",
    "normalizedName": "ginebra tanqueray dry 375ml",
    "brand": "",
    "categoryId": "otros",
    "unit": "375ml",
    "aliases": [
      "ginebra tanqueray dry 375ml",
      "ginebra tanqueray dry"
    ],
    "imageUrl": "/products/foodi-ar/ginebra-tanqueray-dry-375ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_072",
      "s3Path": "dataset/HLKTVWG_0010880_909356737.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-noquis",
    "name": "Ñoquis",
    "normalizedName": "noquis",
    "brand": "",
    "categoryId": "lacteos",
    "unit": "nan",
    "aliases": [
      "noquis"
    ],
    "imageUrl": "/products/foodi-ar/noquis.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Kaló",
      "s3Path": "dataset/CBNGZLF_0040570_1325929521.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-confite-gallito-morenito-bolsa-50u-210gr",
    "name": "Confite Gallito Morenito Bolsa 50U 210Gr",
    "normalizedName": "confite gallito morenito bolsa 50u 210g",
    "brand": "",
    "categoryId": "otros",
    "unit": "210gr",
    "aliases": [
      "confite gallito morenito bolsa 50u 210g",
      "confite gallito morenito bolsa 50u"
    ],
    "imageUrl": "/products/foodi-ar/confite-gallito-morenito-bolsa-50u-210gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0029183_1298965903.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-barilla-spaguettoni-500-gr",
    "name": "Barilla Spaguettoni 500 Gr",
    "normalizedName": "barilla spaguettoni 500g",
    "brand": "",
    "categoryId": "almacen",
    "unit": "500 gr",
    "aliases": [
      "barilla spaguettoni 500g",
      "barilla spaguettoni"
    ],
    "imageUrl": "/products/foodi-ar/barilla-spaguettoni-500-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_150",
      "s3Path": "dataset/CBNGZLF_0029811_1167045515.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-femen-forte-capsula-blanda-400mg-caja-50-09380",
    "name": "Femen Forte Cápsula Blanda 400Mg Caja*50 (09380)",
    "normalizedName": "femen forte capsula blanda 400mg caja 50 09380",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "femen forte capsula blanda 400mg caja 50 09380"
    ],
    "imageUrl": "/products/foodi-ar/femen-forte-capsula-blanda-400mg-caja-50-09380.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0019546_1117919135.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-curcuma-molida-x-100-gr",
    "name": "Curcuma Molida X 100 Gr.",
    "normalizedName": "curcuma molida x 100g",
    "brand": "",
    "categoryId": "otros",
    "unit": "100 gr",
    "aliases": [
      "curcuma molida x 100g",
      "curcuma molida x"
    ],
    "imageUrl": "/products/foodi-ar/curcuma-molida-x-100-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Back up - Mercado Vívet ( BUE)",
      "s3Path": "dataset/CBNGZLF_0041148_1341212873.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-gatorade-active-fresa-kiwi-500",
    "name": "Gatorade Active Fresa Kiwi 500",
    "normalizedName": "gatorade active fresa kiwi 500",
    "brand": "",
    "categoryId": "bebidas",
    "unit": "nan",
    "aliases": [
      "gatorade active fresa kiwi 500"
    ],
    "imageUrl": "/products/foodi-ar/gatorade-active-fresa-kiwi-500.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_009",
      "s3Path": "dataset/HLKTVWG_0010228_883854779.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-tostado-de-jamon-y-queso",
    "name": "Tostado de jamón y queso",
    "normalizedName": "tostado de jamon y queso",
    "brand": "",
    "categoryId": "lacteos",
    "unit": "nan",
    "aliases": [
      "tostado de jamon y queso"
    ],
    "imageUrl": "/products/foodi-ar/tostado-de-jamon-y-queso.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "AVE",
      "storeName": "Tostado Café Club",
      "s3Path": "dataset/PYPBYCR_0000731_803155222.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-guacamole-dip",
    "name": "Guacamole dip",
    "normalizedName": "guacamole dip",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "guacamole dip"
    ],
    "imageUrl": "/products/foodi-ar/guacamole-dip.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Green Salad",
      "s3Path": "dataset/CBNGZLF_0002844_77709503.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-chocolate-nugaton-negro",
    "name": "Chocolate Nugaton negro",
    "normalizedName": "chocolate nugaton negro",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "chocolate nugaton negro"
    ],
    "imageUrl": "/products/foodi-ar/chocolate-nugaton-negro.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0021574_1232220446.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-velas-safari",
    "name": "Velas Safari",
    "normalizedName": "velas safari",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "velas safari"
    ],
    "imageUrl": "/products/foodi-ar/velas-safari.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0028326_1496372350.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-acelga-atado",
    "name": "Acelga (Atado)",
    "normalizedName": "acelga atado",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "acelga atado"
    ],
    "imageUrl": "/products/foodi-ar/acelga-atado.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "MandaleFruta",
      "s3Path": "dataset/CBNGZLF_0038727_1281487504.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-maggi-pasta-de-tomate-113g",
    "name": "Maggi Pasta De Tomate  113G",
    "normalizedName": "maggi pasta de tomate 113g",
    "brand": "",
    "categoryId": "otros",
    "unit": "113g",
    "aliases": [
      "maggi pasta de tomate 113g",
      "maggi pasta de tomate"
    ],
    "imageUrl": "/products/foodi-ar/maggi-pasta-de-tomate-113g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0020042_1121147723.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-yerba-mate-c-palo-union-1kg",
    "name": "Yerba Mate C/ Palo Union 1kg",
    "normalizedName": "yerba mate c palo union 1kg",
    "brand": "",
    "categoryId": "almacen",
    "unit": "1kg",
    "aliases": [
      "yerba mate c palo union 1kg",
      "yerba mate c palo union"
    ],
    "imageUrl": "/products/foodi-ar/yerba-mate-c-palo-union-1kg.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_165",
      "s3Path": "dataset/HLKTVWG_0002323_539630126.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-alfajor-vegano-de-limon-meltaim",
    "name": "Alfajor vegano de limon Meltaím",
    "normalizedName": "alfajor vegano de limon meltaim",
    "brand": "",
    "categoryId": "snacks",
    "unit": "nan",
    "aliases": [
      "alfajor vegano de limon meltaim"
    ],
    "imageUrl": "/products/foodi-ar/alfajor-vegano-de-limon-meltaim.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Back up - Mercado Vívet ( BUE)",
      "s3Path": "dataset/CBNGZLF_0041350_1341213075.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-maquina-de-afeitar-lea-mujer-premium-3-paquete-4un",
    "name": "Máquina de Afeitar LEA Mujer Premium 3 Paquete 4un",
    "normalizedName": "maquina de afeitar lea mujer premium 3 paquete 4un",
    "brand": "",
    "categoryId": "otros",
    "unit": "4un",
    "aliases": [
      "maquina de afeitar lea mujer premium 3 paquete 4un"
    ],
    "imageUrl": "/products/foodi-ar/maquina-de-afeitar-lea-mujer-premium-3-paquete-4un.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_009",
      "s3Path": "dataset/HLKTVWG_0004191_710274345.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-camaron-pelado-mariscos-frescos-454-g-mediano",
    "name": "Camaron Pelado Mariscos Frescos 454 G Mediano",
    "normalizedName": "camaron pelado mariscos frescos 454g mediano",
    "brand": "",
    "categoryId": "otros",
    "unit": "454 g",
    "aliases": [
      "camaron pelado mariscos frescos 454g mediano",
      "camaron pelado mariscos frescos mediano"
    ],
    "imageUrl": "/products/foodi-ar/camaron-pelado-mariscos-frescos-454-g-mediano.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "QLM",
      "storeName": "AS_129",
      "s3Path": "dataset/BSCRBMV_0003562_973236772.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-marlboro-fusion-x-20-un",
    "name": "Marlboro Fusion X 20 Un",
    "normalizedName": "marlboro fusion x 20 un",
    "brand": "",
    "categoryId": "otros",
    "unit": "20 un",
    "aliases": [
      "marlboro fusion x 20 un"
    ],
    "imageUrl": "/products/foodi-ar/marlboro-fusion-x-20-un.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0011461_1144749402.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-papas-fritas-williamsburg",
    "name": "Papas fritas Williamsburg",
    "normalizedName": "papas fritas williamsburg",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "papas fritas williamsburg"
    ],
    "imageUrl": "/products/foodi-ar/papas-fritas-williamsburg.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "LMZ",
      "storeName": "Williamsburg",
      "s3Path": "dataset/HHZYWLV_0005699_1171491304.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-galletas-dulces-aniventuras-funda-400-g-chocolates",
    "name": "Galletas Dulces Aniventuras Funda 400 G Chocolates",
    "normalizedName": "galletas dulces aniventuras funda 400g chocolates",
    "brand": "",
    "categoryId": "snacks",
    "unit": "400 g",
    "aliases": [
      "galletas dulces aniventuras funda 400g chocolates",
      "galletas dulces aniventuras funda chocolates"
    ],
    "imageUrl": "/products/foodi-ar/galletas-dulces-aniventuras-funda-400-g-chocolates.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "QLM",
      "storeName": "AS_129",
      "s3Path": "dataset/BSCRBMV_0006032_1193011989.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-jabon-de-lavar-hipoalergenico-baby-manzanilla-ales-200-gr",
    "name": "Jabón De Lavar Hipoalergenico Baby Manzanilla Ales 200 Gr",
    "normalizedName": "jabon de lavar hipoalergenico baby manzanilla ales 200g",
    "brand": "",
    "categoryId": "otros",
    "unit": "200 gr",
    "aliases": [
      "jabon de lavar hipoalergenico baby manzanilla ales 200g",
      "jabon de lavar hipoalergenico baby manzanilla ales"
    ],
    "imageUrl": "/products/foodi-ar/jabon-de-lavar-hipoalergenico-baby-manzanilla-ales-200-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "QLM",
      "storeName": "AS_129",
      "s3Path": "dataset/BSCRBMV_0007536_1197689495.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-snatts-mediterraneas-tomate",
    "name": "Snatts Mediterraneas Tomate",
    "normalizedName": "snatts mediterraneas tomate",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "snatts mediterraneas tomate"
    ],
    "imageUrl": "/products/foodi-ar/snatts-mediterraneas-tomate.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_016",
      "s3Path": "dataset/CBNGZLF_0045978_1554545772.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-jabon-liquido-intimo-lactacyd-breeze-x-200-ml-7891058018665",
    "name": "Jabón líquido íntimo Lactacyd Breeze x 200 ml. (7891058018665)",
    "normalizedName": "jabon liquido intimo lactacyd breeze x 200ml 7891058018665",
    "brand": "",
    "categoryId": "otros",
    "unit": "200 ml",
    "aliases": [
      "jabon liquido intimo lactacyd breeze x 200ml 7891058018665",
      "jabon liquido intimo lactacyd breeze x 7891058018665"
    ],
    "imageUrl": "/products/foodi-ar/jabon-liquido-intimo-lactacyd-breeze-x-200-ml-7891058018665.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_009",
      "s3Path": "dataset/HLKTVWG_0009198_868906155.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-thermocarnitin-xl-powergym-10ml",
    "name": "Thermocarnitin Xl Powergym 10ml",
    "normalizedName": "thermocarnitin xl powergym 10ml",
    "brand": "",
    "categoryId": "otros",
    "unit": "10ml",
    "aliases": [
      "thermocarnitin xl powergym 10ml",
      "thermocarnitin xl powergym"
    ],
    "imageUrl": "/products/foodi-ar/thermocarnitin-xl-powergym-10ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_016",
      "s3Path": "dataset/CBNGZLF_0046569_1584667213.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-suavitel-adios-al-planc-sin-enjuag",
    "name": "Suavitel Adios Al Planc Sin Enjuag",
    "normalizedName": "suavitel adios al planc sin enjuag",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "suavitel adios al planc sin enjuag"
    ],
    "imageUrl": "/products/foodi-ar/suavitel-adios-al-planc-sin-enjuag.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "57380 (BOE)",
      "s3Path": "dataset/DDLRZFC_0015297_1073987029.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-bebida-energizante-red-bull-250-cc",
    "name": "Bebida Energizante Red Bull 250 Cc.",
    "normalizedName": "bebida energizante red bull 250 cc",
    "brand": "",
    "categoryId": "bebidas",
    "unit": "nan",
    "aliases": [
      "bebida energizante red bull 250 cc"
    ],
    "imageUrl": "/products/foodi-ar/bebida-energizante-red-bull-250-cc.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "ROS",
      "storeName": "Siempre Bebidas",
      "s3Path": "dataset/KLLRBTH_0005376_1326334183.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-s-snacks-chee-zees-45-gr",
    "name": "S Snacks Chee Zees 45 Gr",
    "normalizedName": "s snacks chee zees 45g",
    "brand": "",
    "categoryId": "snacks",
    "unit": "45 gr",
    "aliases": [
      "s snacks chee zees 45g",
      "s snacks chee zees"
    ],
    "imageUrl": "/products/foodi-ar/s-snacks-chee-zees-45-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_192",
      "s3Path": "dataset/CBNGZLF_0020114_1122799265.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-croissant-6-x-140-g",
    "name": "Croissant 6 X 140 G",
    "normalizedName": "croissant 6 x 140g",
    "brand": "",
    "categoryId": "otros",
    "unit": "140 g",
    "aliases": [
      "croissant 6 x 140g",
      "croissant 6 x"
    ],
    "imageUrl": "/products/foodi-ar/croissant-6-x-140-g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_009",
      "s3Path": "dataset/HLKTVWG_0010102_883840638.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-energizante-monster-energy-473-ml",
    "name": "Energizante Monster Energy 473 Ml",
    "normalizedName": "energizante monster energy 473ml",
    "brand": "",
    "categoryId": "bebidas",
    "unit": "473 ml",
    "aliases": [
      "energizante monster energy 473ml",
      "energizante monster energy"
    ],
    "imageUrl": "/products/foodi-ar/energizante-monster-energy-473-ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0023514_1129370751.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-chipa",
    "name": "Chipá",
    "normalizedName": "chipa",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "chipa"
    ],
    "imageUrl": "/products/foodi-ar/chipa.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Donut Makers",
      "s3Path": "dataset/CBNGZLF_0036948_1227546075.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-cerveza-hoegaarden-33-cl",
    "name": "Cerveza Hoegaarden 33 Cl",
    "normalizedName": "cerveza hoegaarden 33 cl",
    "brand": "",
    "categoryId": "bebidas",
    "unit": "nan",
    "aliases": [
      "cerveza hoegaarden 33 cl"
    ],
    "imageUrl": "/products/foodi-ar/cerveza-hoegaarden-33-cl.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_150",
      "s3Path": "dataset/CBNGZLF_0030387_1167888068.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-kit-cucuruchos-rocklets",
    "name": "Kit cucuruchos Rocklets",
    "normalizedName": "kit cucuruchos rocklets",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "kit cucuruchos rocklets"
    ],
    "imageUrl": "/products/foodi-ar/kit-cucuruchos-rocklets.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "LMZ",
      "storeName": "Grido",
      "s3Path": "dataset/HHZYWLV_0007742_1326480091.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-dos-pinos-queso-crema-in-line-210g",
    "name": "Dos Pinos Queso Crema In Line 210G",
    "normalizedName": "dos pinos queso crema in line 210g",
    "brand": "",
    "categoryId": "otros",
    "unit": "210g",
    "aliases": [
      "dos pinos queso crema in line 210g",
      "dos pinos queso crema in line"
    ],
    "imageUrl": "/products/foodi-ar/dos-pinos-queso-crema-in-line-210g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0014643_1073843099.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-barilla-lasagne-500-gr",
    "name": "Barilla Lasagne 500 Gr",
    "normalizedName": "barilla lasagne 500g",
    "brand": "",
    "categoryId": "almacen",
    "unit": "500 gr",
    "aliases": [
      "barilla lasagne 500g",
      "barilla lasagne"
    ],
    "imageUrl": "/products/foodi-ar/barilla-lasagne-500-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_150",
      "s3Path": "dataset/CBNGZLF_0029801_1167045505.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-jugo-welch-de-uva-10oz-210-10-oz",
    "name": "Jugo Welch De Uva 10Oz 210 10 Oz",
    "normalizedName": "jugo welch de uva 10oz 210 10 oz",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "jugo welch de uva 10oz 210 10 oz"
    ],
    "imageUrl": "/products/foodi-ar/jugo-welch-de-uva-10oz-210-10-oz.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "QLM",
      "storeName": "AS_129",
      "s3Path": "dataset/BSCRBMV_0001702_809330008.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-indian-chai-lata-100-gr",
    "name": "Indian Chai lata (100 gr.)",
    "normalizedName": "indian chai lata 100g",
    "brand": "",
    "categoryId": "almacen",
    "unit": "100 gr",
    "aliases": [
      "indian chai lata 100g",
      "indian chai lata"
    ],
    "imageUrl": "/products/foodi-ar/indian-chai-lata-100-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "Tea Connection",
      "s3Path": "dataset/DDLRZFC_0027290_1310994802.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-trop-herbal-limon-hierbabuena-2-5-l-1649",
    "name": "Trop Herbal Limon Hierbabuena 2.5 L  1649",
    "normalizedName": "trop herbal limon hierbabuena 25l 1649",
    "brand": "",
    "categoryId": "otros",
    "unit": "2.5 l",
    "aliases": [
      "trop herbal limon hierbabuena 25l 1649",
      "trop herbal limon hierbabuena 1649"
    ],
    "imageUrl": "/products/foodi-ar/trop-herbal-limon-hierbabuena-2-5-l-1649.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "PLR",
      "storeName": "Mostaza",
      "s3Path": "dataset/RVSSQYC_0003988_1230791523.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-gall-bagley-opera-55gr",
    "name": "Gall Bagley Opera 55Gr",
    "normalizedName": "gall bagley opera 55g",
    "brand": "",
    "categoryId": "snacks",
    "unit": "55gr",
    "aliases": [
      "gall bagley opera 55g",
      "gall bagley opera"
    ],
    "imageUrl": "/products/foodi-ar/gall-bagley-opera-55gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_004",
      "s3Path": "dataset/RSDQDRN_0014798_1177427093.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-pan-melcochon-cero",
    "name": "Pan Melcochon Cero",
    "normalizedName": "pan melcochon cero",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "pan melcochon cero"
    ],
    "imageUrl": "/products/foodi-ar/pan-melcochon-cero.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_009",
      "s3Path": "dataset/HLKTVWG_0019879_1190333689.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-queso-mozarella-kiosko-200-g",
    "name": "Queso Mozarella Kiosko 200 G",
    "normalizedName": "queso mozarella kiosko 200g",
    "brand": "",
    "categoryId": "lacteos",
    "unit": "200 g",
    "aliases": [
      "queso mozarella kiosko 200g",
      "queso mozarella kiosko"
    ],
    "imageUrl": "/products/foodi-ar/queso-mozarella-kiosko-200-g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_072",
      "s3Path": "dataset/HLKTVWG_0017152_1135995713.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-bejitarian-poke",
    "name": "Bejitarian poke",
    "normalizedName": "bejitarian poke",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "bejitarian poke"
    ],
    "imageUrl": "/products/foodi-ar/bejitarian-poke.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Katsu - Asian Street Food",
      "s3Path": "dataset/CBNGZLF_0040602_1326029789.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-tabla-classic-mania-24-unidades",
    "name": "Tabla classic Mania (24 unidades)",
    "normalizedName": "tabla classic mania 24 unidades",
    "brand": "",
    "categoryId": "otros",
    "unit": "24 unidades",
    "aliases": [
      "tabla classic mania 24 unidades"
    ],
    "imageUrl": "/products/foodi-ar/tabla-classic-mania-24-unidades.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "ROS",
      "storeName": "Sushimanía",
      "s3Path": "dataset/KLLRBTH_0001803_947405178.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-arroz-fortificado-envejecido-casa-del-arroz-2-kg",
    "name": "Arroz Fortificado Envejecido Casa Del Arroz 2 Kg",
    "normalizedName": "arroz fortificado envejecido casa del arroz 2kg",
    "brand": "",
    "categoryId": "otros",
    "unit": "2 kg",
    "aliases": [
      "arroz fortificado envejecido casa del arroz 2kg",
      "arroz fortificado envejecido casa del arroz"
    ],
    "imageUrl": "/products/foodi-ar/arroz-fortificado-envejecido-casa-del-arroz-2-kg.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0021835_1129332973.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-ocean-spray-diet-cramber-1-89l",
    "name": "Ocean Spray Diet Cramber 1.89L",
    "normalizedName": "ocean spray diet cramber 189l",
    "brand": "",
    "categoryId": "otros",
    "unit": "1.89l",
    "aliases": [
      "ocean spray diet cramber 189l",
      "ocean spray diet cramber"
    ],
    "imageUrl": "/products/foodi-ar/ocean-spray-diet-cramber-1-89l.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_004",
      "s3Path": "dataset/RSDQDRN_0011816_1147247537.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-desinfectante-fabuloso-1000-ml-floral",
    "name": "Desinfectante Fabuloso 1000 Ml Floral",
    "normalizedName": "desinfectante fabuloso 1000ml floral",
    "brand": "",
    "categoryId": "limpieza",
    "unit": "1000 ml",
    "aliases": [
      "desinfectante fabuloso 1000ml floral",
      "desinfectante fabuloso floral"
    ],
    "imageUrl": "/products/foodi-ar/desinfectante-fabuloso-1000-ml-floral.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "LMZ",
      "storeName": "AS_204",
      "s3Path": "dataset/HHZYWLV_0002728_1106617136.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-rothmans-ks-20",
    "name": "Rothmans ks 20",
    "normalizedName": "rothmans ks 20",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "rothmans ks 20"
    ],
    "imageUrl": "/products/foodi-ar/rothmans-ks-20.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "LPT",
      "storeName": "Kiosco 365",
      "s3Path": "dataset/VSXSWWR_0005332_1146271763.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-philip-morris-box-10",
    "name": "Philip Morris box 10",
    "normalizedName": "philip morris box 10",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "philip morris box 10"
    ],
    "imageUrl": "/products/foodi-ar/philip-morris-box-10.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "LPT",
      "storeName": "Kiosco 365",
      "s3Path": "dataset/VSXSWWR_0006058_1147515289.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-hisopos-extrafinos-caricia-100-und",
    "name": "Hisopos Extrafinos Caricia 100 Und",
    "normalizedName": "hisopos extrafinos caricia 100 und",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "hisopos extrafinos caricia 100 und"
    ],
    "imageUrl": "/products/foodi-ar/hisopos-extrafinos-caricia-100-und.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "QLM",
      "storeName": "AS_129",
      "s3Path": "dataset/BSCRBMV_0009829_1202090953.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-ampolla-vitane-revitalizante-plus-caja-4un",
    "name": "Ampolla Vitane Revitalizante Plus Caja 4Un",
    "normalizedName": "ampolla vitane revitalizante plus caja 4un",
    "brand": "",
    "categoryId": "perfumeria",
    "unit": "4un",
    "aliases": [
      "ampolla vitane revitalizante plus caja 4un"
    ],
    "imageUrl": "/products/foodi-ar/ampolla-vitane-revitalizante-plus-caja-4un.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0024080_1277658618.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-lavandina-ayudin-frag-lavanda-1l",
    "name": "Lavandina Ayudin Frag Lavanda 1L",
    "normalizedName": "lavandina ayudin frag lavanda 1l",
    "brand": "",
    "categoryId": "limpieza",
    "unit": "1l",
    "aliases": [
      "lavandina ayudin frag lavanda 1l",
      "lavandina ayudin frag lavanda"
    ],
    "imageUrl": "/products/foodi-ar/lavandina-ayudin-frag-lavanda-1l.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_004",
      "s3Path": "dataset/RSDQDRN_0014669_1177426695.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-hersheys-milk-43g",
    "name": "Hersheys Milk 43G",
    "normalizedName": "hersheys milk 43g",
    "brand": "",
    "categoryId": "otros",
    "unit": "43g",
    "aliases": [
      "hersheys milk 43g",
      "hersheys milk"
    ],
    "imageUrl": "/products/foodi-ar/hersheys-milk-43g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "COR",
      "storeName": "AS_072",
      "s3Path": "dataset/HLKTVWG_0015043_1063011257.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-my-way-agua-de-coco-con-pulpa-310ml",
    "name": "My Way Agua De Coco Con Pulpa 310Ml",
    "normalizedName": "my way agua de coco con pulpa 310ml",
    "brand": "",
    "categoryId": "otros",
    "unit": "310ml",
    "aliases": [
      "my way agua de coco con pulpa 310ml",
      "my way agua de coco con pulpa"
    ],
    "imageUrl": "/products/foodi-ar/my-way-agua-de-coco-con-pulpa-310ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0020263_1121147966.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-kitchen-limpion-estp-tint-60x40-cm",
    "name": "Kitchen Limpion Estp/Tint 60X40 Cm",
    "normalizedName": "kitchen limpion estp tint 60x40 cm",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "kitchen limpion estp tint 60x40 cm"
    ],
    "imageUrl": "/products/foodi-ar/kitchen-limpion-estp-tint-60x40-cm.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "QLM",
      "storeName": "AS_129",
      "s3Path": "dataset/BSCRBMV_0009822_1202090664.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-underwood-jamon-endiablado-4-25-oz",
    "name": "Underwood Jamon Endiablado 4.25 Oz",
    "normalizedName": "underwood jamon endiablado 425 oz",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "underwood jamon endiablado 425 oz"
    ],
    "imageUrl": "/products/foodi-ar/underwood-jamon-endiablado-4-25-oz.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_150",
      "s3Path": "dataset/CBNGZLF_0029305_1167044996.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-cheetos-fritolays-255-10-gr",
    "name": "Cheetos Fritolays 255 10 Gr",
    "normalizedName": "cheetos fritolays 255 10g",
    "brand": "",
    "categoryId": "otros",
    "unit": "10 gr",
    "aliases": [
      "cheetos fritolays 255 10g",
      "cheetos fritolays 255"
    ],
    "imageUrl": "/products/foodi-ar/cheetos-fritolays-255-10-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0029279_1298966002.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-collar-reflectivo-aurora-talla-l-circunf-cuello-40-62cm-x-anch-2-5cm-hasta-30kg",
    "name": "Collar Reflectivo Aurora Talla L  (Circunf. Cuello 40-62cm x Anch 2.5cm) Hasta 30kg",
    "normalizedName": "collar reflectivo aurora talla l circunf cuello 40-62cm x anch 25cm hasta 30kg",
    "brand": "",
    "categoryId": "otros",
    "unit": "30kg",
    "aliases": [
      "collar reflectivo aurora talla l circunf cuello 40-62cm x anch 25cm hasta 30kg",
      "collar reflectivo aurora talla l circunf cuello 40-62cm x anch 25cm hasta"
    ],
    "imageUrl": "/products/foodi-ar/collar-reflectivo-aurora-talla-l-circunf-cuello-40-62cm-x-anch-2-5cm-hasta-30kg.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_210",
      "s3Path": "dataset/CBNGZLF_0015526_1078035171.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-roll-de-pollo-nueva-receta-bebida",
    "name": "Roll de pollo (nueva receta) + bebida",
    "normalizedName": "roll de pollo nueva receta bebida",
    "brand": "",
    "categoryId": "almacen",
    "unit": "nan",
    "aliases": [
      "roll de pollo nueva receta bebida"
    ],
    "imageUrl": "/products/foodi-ar/roll-de-pollo-nueva-receta-bebida.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "Green Eat",
      "s3Path": "dataset/CBNGZLF_0006903_612931047.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-cebion-vitamina-c-naranja-tabletas-500-mg-unidad",
    "name": "Cebion Vitamina C Naranja Tabletas 500 Mg Unidad",
    "normalizedName": "cebion vitamina c naranja tabletas 500 mg unidad",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "cebion vitamina c naranja tabletas 500 mg unidad"
    ],
    "imageUrl": "/products/foodi-ar/cebion-vitamina-c-naranja-tabletas-500-mg-unidad.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0017851_1191390006.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-pozuelo-bokitas-c-queso-tu-141g",
    "name": "Pozuelo Bokitas C/Queso Tu.141G",
    "normalizedName": "pozuelo bokitas c queso tu 141g",
    "brand": "",
    "categoryId": "snacks",
    "unit": "141g",
    "aliases": [
      "pozuelo bokitas c queso tu 141g",
      "pozuelo bokitas c queso tu"
    ],
    "imageUrl": "/products/foodi-ar/pozuelo-bokitas-c-queso-tu-141g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "AS_091",
      "s3Path": "dataset/DDLRZFC_0018902_1116730135.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-cafe-tosado-y-molido-starbucks-house-blend-tostado-medio-bolsa-250g",
    "name": "Café Tosado Y Molido Starbucks House Blend Tostado Medio Bolsa 250G",
    "normalizedName": "cafe tosado y molido starbucks house blend tostado medio bolsa 250g",
    "brand": "",
    "categoryId": "otros",
    "unit": "250g",
    "aliases": [
      "cafe tosado y molido starbucks house blend tostado medio bolsa 250g",
      "cafe tosado y molido starbucks house blend tostado medio bolsa"
    ],
    "imageUrl": "/products/foodi-ar/cafe-tosado-y-molido-starbucks-house-blend-tostado-medio-bolsa-250g.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0025789_1277660424.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-suero-rehid-electrolit-uva-625ml",
    "name": "Suero Rehid Electrolit Uva 625Ml",
    "normalizedName": "suero rehid electrolit uva 625ml",
    "brand": "",
    "categoryId": "otros",
    "unit": "625ml",
    "aliases": [
      "suero rehid electrolit uva 625ml",
      "suero rehid electrolit uva"
    ],
    "imageUrl": "/products/foodi-ar/suero-rehid-electrolit-uva-625ml.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0028251_1298964940.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-kion",
    "name": "Kion",
    "normalizedName": "kion",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "kion"
    ],
    "imageUrl": "/products/foodi-ar/kion.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_015",
      "s3Path": "dataset/RSDQDRN_0004096_837293673.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-dos-pinos-deligurt-topping-tapita-150-gr",
    "name": "Dos Pinos Deligurt Topping Tapita 150 Gr",
    "normalizedName": "dos pinos deligurt topping tapita 150g",
    "brand": "",
    "categoryId": "lacteos",
    "unit": "150 gr",
    "aliases": [
      "dos pinos deligurt topping tapita 150g",
      "dos pinos deligurt topping tapita"
    ],
    "imageUrl": "/products/foodi-ar/dos-pinos-deligurt-topping-tapita-150-gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "MDZ",
      "storeName": "AS_003",
      "s3Path": "dataset/RSDQDRN_0019339_1194812618.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-galletas-rellenas-oreo-54-g-original",
    "name": "Galletas Rellenas Oreo 54 G Original",
    "normalizedName": "galletas rellenas oreo 54g original",
    "brand": "",
    "categoryId": "snacks",
    "unit": "54 g",
    "aliases": [
      "galletas rellenas oreo 54g original",
      "galletas rellenas oreo original"
    ],
    "imageUrl": "/products/foodi-ar/galletas-rellenas-oreo-54-g-original.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "PLR",
      "storeName": "AS_035",
      "s3Path": "dataset/RVSSQYC_0000763_973247946.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-ceviche-nikkei",
    "name": "Ceviche nikkei",
    "normalizedName": "ceviche nikkei",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "ceviche nikkei"
    ],
    "imageUrl": "/products/foodi-ar/ceviche-nikkei.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BOE",
      "storeName": "Paru Sushi",
      "s3Path": "dataset/DDLRZFC_0026437_1224812582.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-california-roll-10-uds",
    "name": "California roll (10 uds.)",
    "normalizedName": "california roll 10 uds",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "california roll 10 uds"
    ],
    "imageUrl": "/products/foodi-ar/california-roll-10-uds.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "LPT",
      "storeName": "Osaki Sushi",
      "s3Path": "dataset/VSXSWWR_0000928_227067135.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-langostinos",
    "name": "Langostinos",
    "normalizedName": "langostinos",
    "brand": "",
    "categoryId": "otros",
    "unit": "nan",
    "aliases": [
      "langostinos"
    ],
    "imageUrl": "/products/foodi-ar/langostinos.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "TUC",
      "storeName": "El Club de la Milanesa",
      "s3Path": "dataset/QDKLXPQ_0000559_1120523458.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-equilibrio-adult-sensitive-cordero-small-7-5-kg-01e072",
    "name": "Equilibrio Adult Sensitive Cordero Small 7.5 Kg 01E072",
    "normalizedName": "equilibrio adult sensitive cordero small 75kg 01e072",
    "brand": "",
    "categoryId": "otros",
    "unit": "7.5 kg",
    "aliases": [
      "equilibrio adult sensitive cordero small 75kg 01e072",
      "equilibrio adult sensitive cordero small 01e072"
    ],
    "imageUrl": "/products/foodi-ar/equilibrio-adult-sensitive-cordero-small-7-5-kg-01e072.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_016",
      "s3Path": "dataset/CBNGZLF_0013389_1038144614.png"
    },
    "status": "review"
  },
  {
    "id": "foodi-ar-cacao-nesquik-180gr",
    "name": "Cacao Nesquik 180Gr",
    "normalizedName": "cacao nesquik 180g",
    "brand": "",
    "categoryId": "otros",
    "unit": "180gr",
    "aliases": [
      "cacao nesquik 180g",
      "cacao nesquik"
    ],
    "imageUrl": "/products/foodi-ar/cacao-nesquik-180gr.webp",
    "imageSource": "foodi_ml",
    "imageStatus": "needs_review",
    "source": {
      "dataset": "FooDI-ML",
      "countryCode": "AR",
      "cityCode": "BUE",
      "storeName": "AS_053",
      "s3Path": "dataset/CBNGZLF_0033245_1177444100.png"
    },
    "status": "review"
  }
]
