import {
  Comercio,
  Distribuidora,
  Product,
  Category,
  DistributorCard,
  Order,
  DashboardKPIs
} from './types'

// Categories
export const categories: Category[] = [
  { id: '1',  name: 'Bebidas',           iconName: 'bottle',    image: '/categorias/01_bebidas.png' },
  { id: '2',  name: 'Almacén',           iconName: 'boxes',     image: '/categorias/02_almacen.png' },
  { id: '3',  name: 'Limpieza',          iconName: 'sparkles',  image: '/categorias/03_limpieza.png' },
  { id: '4',  name: 'Lácteos',           iconName: 'milk',      image: '/categorias/04_lacteos.png' },
  { id: '5',  name: 'Panadería',         iconName: 'wheat',     image: '/categorias/05_panaderia.png' },
  { id: '6',  name: 'Snacks',            iconName: 'package',   image: '/categorias/06_snacks.png' },
  { id: '7',  name: 'Fiambres',          iconName: 'badge',     image: '/categorias/07_fiambres.png' },
  { id: '8',  name: 'Congelados',        iconName: 'snowflake', image: '/categorias/08_congelados.png' },
  { id: '9',  name: 'Golosinas y Kiosco',iconName: 'package',   image: '/categorias/09_golosinas_kiosco.png' },
  { id: '10', name: 'Perfumería',        iconName: 'sparkles',  image: '/categorias/10_perfumeria.png' },
  { id: '11', name: 'Mascotas',          iconName: 'package',   image: '/categorias/11_mascotas.png' },
  { id: '12', name: 'Otros',             iconName: 'boxes',     image: '/categorias/12_otros.png' },
]

// Mock Comercios
export const mockComercios: Comercio[] = [
  {
    id: 'com-1',
    email: 'almacen.don.pedro@email.com',
    role: 'comercio',
    storeName: 'Almacén Don Pedro',
    razonSocial: 'García, Roberto Marcelo',
    cuit: '20-28741632-9',
    phone: '+54 11 4567-8901',
    address: 'Av. Mitre 1234',
    location: {
      lat: -34.6629,
      lng: -58.3659,
      city: 'Avellaneda',
      province: 'Buenos Aires',
      provinceSlug: 'buenos-aires',
      citySlug: 'avellaneda',
      locationKey: 'buenos-aires:avellaneda',
    },
    createdAt: '2024-01-15',
  },
  {
    id: 'com-2',
    email: 'kiosco.maria@email.com',
    role: 'comercio',
    storeName: 'Kiosco María',
    razonSocial: 'López, María Inés',
    cuit: '27-31456789-3',
    phone: '+54 11 4567-1234',
    address: 'Calle 9 de Julio 567',
    location: {
      lat: -34.7263,
      lng: -58.4063,
      city: 'Lanús',
      province: 'Buenos Aires',
      provinceSlug: 'buenos-aires',
      citySlug: 'lanus',
      locationKey: 'buenos-aires:lanus',
    },
    createdAt: '2024-02-01',
  },
]

// Mock Distribuidoras
export const mockDistribuidoras: Distribuidora[] = [
  {
    id: 'dist-1',
    email: 'contacto@bebidassur.com',
    role: 'distribuidora',
    companyName: 'Bebidas del Sur',
    razonSocial: 'Bebidas del Sur S.R.L.',
    cuit: '30-71234567-4',
    phone: '+54 11 4321-5678',
    address: 'Parque Industrial Quilmes',
    coverageRadiusKm: 25,
    minOrder: 15000,
    deliveryTimeLabel: '24 horas hábiles',
    deliveryTimeHours: 24,
    deliveryZones: ['Quilmes', 'Avellaneda', 'Lanús', 'Berazategui'],
    deliveryHours: 'Lunes a Viernes · 8 a 17hs',
    location: {
      lat: -34.7223,
      lng: -58.2545,
      city: 'Quilmes',
    },
    createdAt: '2024-01-01',
  },
  {
    id: 'dist-2',
    email: 'ventas@lacteosfrescos.com',
    role: 'distribuidora',
    companyName: 'Lácteos Frescos SRL',
    razonSocial: 'Lácteos Frescos S.R.L.',
    cuit: '30-68943211-7',
    phone: '+54 11 4321-8765',
    address: 'Av. Calchaquí 4500',
    coverageRadiusKm: 15,
    minOrder: 8000,
    deliveryTimeLabel: 'Mismo día',
    deliveryTimeHours: 4,
    deliveryZones: ['Quilmes', 'Avellaneda', 'Lomas de Zamora'],
    deliveryHours: 'Lunes a Sábado · 6 a 14hs',
    location: {
      lat: -34.7163,
      lng: -58.3063,
      city: 'Quilmes',
    },
    createdAt: '2024-01-10',
  },
  {
    id: 'dist-3',
    email: 'pedidos@panaderosunidos.com',
    role: 'distribuidora',
    companyName: 'Panaderos Unidos',
    razonSocial: 'Panaderos Unidos Coop. Ltda.',
    cuit: '30-59874123-6',
    phone: '+54 11 4567-9999',
    address: 'Calle Alsina 890',
    coverageRadiusKm: 10,
    minOrder: 5000,
    deliveryTimeLabel: 'En 2 horas',
    deliveryTimeHours: 2,
    deliveryZones: ['Avellaneda', 'Lanús'],
    deliveryHours: 'Lunes a Sábado · 5 a 12hs',
    location: {
      lat: -34.6629,
      lng: -58.3659,
      city: 'Avellaneda',
    },
    createdAt: '2024-01-20',
  },
  {
    id: 'dist-4',
    email: 'info@megadistribuidora.com',
    role: 'distribuidora',
    companyName: 'Mega Distribuidora',
    razonSocial: 'Mega Distribuidora S.A.',
    cuit: '30-71987654-1',
    phone: '+54 11 5555-1234',
    address: 'Ruta 2 km 5',
    coverageRadiusKm: 30,
    minOrder: 25000,
    deliveryTimeLabel: '48 horas hábiles',
    deliveryTimeHours: 48,
    deliveryZones: ['Lanús', 'Avellaneda', 'Quilmes', 'Lomas de Zamora', 'Berazategui'],
    deliveryHours: 'Lunes a Viernes · 8 a 18hs',
    location: {
      lat: -34.7563,
      lng: -58.3863,
      city: 'Lanús',
    },
    createdAt: '2024-02-01',
  },
]

// Distributor cards for comercio home
export const mockDistributorCards: DistributorCard[] = [
  {
    id: 'dist-1',
    companyName: 'Bebidas del Sur',
    initials: 'BS',
    distance: '3.2 km',
    deliveryInfo: 'Entrega en 24hs',
    minOrder: 15000,
    productCount: 156,
    categories: ['Bebidas', 'Snacks'],
  },
  {
    id: 'dist-2',
    companyName: 'Lácteos Frescos SRL',
    initials: 'LF',
    distance: '1.8 km',
    deliveryInfo: 'Entrega mismo día',
    minOrder: 8000,
    productCount: 89,
    categories: ['Lácteos', 'Fiambres'],
  },
  {
    id: 'dist-3',
    companyName: 'Panaderos Unidos',
    initials: 'PU',
    distance: '0.5 km',
    deliveryInfo: 'Entrega en 2hs',
    minOrder: 5000,
    productCount: 42,
    categories: ['Panadería'],
  },
  {
    id: 'dist-4',
    companyName: 'Mega Distribuidora',
    initials: 'MD',
    distance: '4.5 km',
    deliveryInfo: 'Entrega en 48hs',
    minOrder: 25000,
    productCount: 320,
    categories: ['Almacén', 'Limpieza', 'Bebidas'],
  },
]

// Products by distribuidora
export const mockProducts: Product[] = [
  // Bebidas del Sur products
  {
    id: 'prod-1',
    distribuidoraId: 'dist-1',
    name: 'Coca-Cola 2.25L',
    category: 'Bebidas',
    price: 1850,
    stock: 240,
    description: 'Gaseosa Coca-Cola botella 2.25 litros',
    active: true,
  status: 'active',
    rating: 4.9,
    reviewCount: 124,
  },
  {
    id: 'prod-2',
    distribuidoraId: 'dist-1',
    name: 'Sprite 2.25L',
    category: 'Bebidas',
    price: 1750,
    stock: 180,
    description: 'Gaseosa Sprite botella 2.25 litros',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: 'prod-3',
    distribuidoraId: 'dist-1',
    name: 'Agua Mineral Villavicencio 1.5L',
    category: 'Bebidas',
    price: 980,
    stock: 320,
    description: 'Agua mineral sin gas 1.5 litros',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 211,
  },
  {
    id: 'prod-4',
    distribuidoraId: 'dist-1',
    name: 'Cerveza Quilmes 1L',
    category: 'Bebidas',
    price: 2100,
    stock: 150,
    description: 'Cerveza Quilmes retornable 1 litro',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 73,
  },
  {
    id: 'prod-5',
    distribuidoraId: 'dist-1',
    name: 'Papas Lays Clásicas 270g',
    category: 'Snacks',
    price: 2450,
    stock: 8,
    description: 'Papas fritas Lays sabor clásico',
    active: true,
  status: 'active',
    rating: 4.5,
    reviewCount: 38,
  },
  // Lácteos Frescos products
  {
    id: 'prod-6',
    distribuidoraId: 'dist-2',
    name: 'Leche La Serenísima 1L',
    category: 'Lácteos',
    price: 1250,
    stock: 7,
    description: 'Leche entera La Serenísima sachet 1 litro',
    active: true,
  status: 'active',
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: 'prod-7',
    distribuidoraId: 'dist-2',
    name: 'Yogur Activia Natural 190g',
    category: 'Lácteos',
    price: 890,
    stock: 120,
    description: 'Yogur Activia natural sin azúcar',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 55,
  },
  {
    id: 'prod-8',
    distribuidoraId: 'dist-2',
    name: 'Queso Cremoso Tregar 1kg',
    category: 'Lácteos',
    price: 8500,
    stock: 45,
    description: 'Queso cremoso Tregar por kilo',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 94,
  },
  {
    id: 'prod-9',
    distribuidoraId: 'dist-2',
    name: 'Jamón Cocido Paladini 200g',
    category: 'Fiambres',
    price: 3200,
    stock: 60,
    description: 'Jamón cocido Paladini feteado',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 47,
  },
  {
    id: 'prod-10',
    distribuidoraId: 'dist-2',
    name: 'Manteca La Serenísima 200g',
    category: 'Lácteos',
    price: 2100,
    stock: 80,
    description: 'Manteca La Serenísima pan 200g',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 103,
  },
  // Panaderos Unidos products
  {
    id: 'prod-11',
    distribuidoraId: 'dist-3',
    name: 'Pan Francés (docena)',
    category: 'Panadería',
    price: 1200,
    stock: 100,
    description: 'Pan francés fresco, docena',
    active: true,
  status: 'active',
    rating: 4.9,
    reviewCount: 187,
  },
  {
    id: 'prod-12',
    distribuidoraId: 'dist-3',
    name: 'Medialunas (docena)',
    category: 'Panadería',
    price: 2800,
    stock: 50,
    description: 'Medialunas de manteca, docena',
    active: true,
  status: 'active',
    rating: 5.0,
    reviewCount: 142,
  },
  {
    id: 'prod-13',
    distribuidoraId: 'dist-3',
    name: 'Pan Lactal Bimbo 500g',
    category: 'Panadería',
    price: 1650,
    stock: 75,
    description: 'Pan lactal blanco Bimbo',
    active: true,
  status: 'active',
    rating: 4.4,
    reviewCount: 61,
  },
  {
    id: 'prod-14',
    distribuidoraId: 'dist-3',
    name: 'Facturas Surtidas (docena)',
    category: 'Panadería',
    price: 3500,
    stock: 30,
    description: 'Facturas surtidas frescas',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 95,
  },
  // Mega Distribuidora products
  {
    id: 'prod-15',
    distribuidoraId: 'dist-4',
    name: 'Arroz Gallo Oro 1kg',
    category: 'Almacén',
    price: 1450,
    stock: 200,
    description: 'Arroz largo fino Gallo Oro',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 78,
  },
  {
    id: 'prod-16',
    distribuidoraId: 'dist-4',
    name: 'Fideos Matarazzo 500g',
    category: 'Almacén',
    price: 980,
    stock: 180,
    description: 'Fideos spaghetti Matarazzo',
    active: true,
  status: 'active',
    rating: 4.5,
    reviewCount: 52,
  },
  {
    id: 'prod-17',
    distribuidoraId: 'dist-4',
    name: 'Lavandina Ayudín 2L',
    category: 'Limpieza',
    price: 1100,
    stock: 120,
    description: 'Lavandina concentrada Ayudín',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 44,
  },
  {
    id: 'prod-18',
    distribuidoraId: 'dist-4',
    name: 'Detergente Magistral 750ml',
    category: 'Limpieza',
    price: 1850,
    stock: 90,
    description: 'Detergente Magistral multiuso',
    active: true,
  status: 'active',
    rating: 4.3,
    reviewCount: 29,
  },
  {
    id: 'prod-19',
    distribuidoraId: 'dist-4',
    name: 'Aceite Cocinero 1.5L',
    category: 'Almacén',
    price: 2200,
    stock: 150,
    description: 'Aceite de girasol Cocinero',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 66,
  },
  {
    id: 'prod-20',
    distribuidoraId: 'dist-4',
    name: 'Azúcar Ledesma 1kg',
    category: 'Almacén',
    price: 1050,
    stock: 220,
    description: 'Azúcar blanca Ledesma',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 81,
  },

  // ── Bebidas del Sur — productos adicionales ────────────────────────────────
  {
    id: 'prod-21',
    distribuidoraId: 'dist-1',
    name: 'Fanta Naranja 2.25L',
    category: 'Bebidas',
    price: 1780,
    stock: 160,
    description: 'Gaseosa Fanta naranja botella 2.25 litros',
    active: true,
  status: 'active',
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: 'prod-22',
    distribuidoraId: 'dist-1',
    name: 'Gatorade Naranja 500ml',
    category: 'Bebidas',
    price: 1350,
    stock: 200,
    description: 'Bebida deportiva Gatorade sabor naranja',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 43,
  },
  {
    id: 'prod-23',
    distribuidoraId: 'dist-1',
    name: 'Jugo Cepita Naranja 1L (x12)',
    category: 'Bebidas',
    price: 14400,
    stock: 40,
    description: 'Caja de 12 jugos Cepita naranja 1 litro',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 91,
  },
  {
    id: 'prod-24',
    distribuidoraId: 'dist-1',
    name: 'Schweppes Tónica 1.5L',
    category: 'Bebidas',
    price: 1620,
    stock: 90,
    description: 'Agua tónica Schweppes botella 1.5 litros',
    active: true,
  status: 'active',
    rating: 4.4,
    reviewCount: 32,
  },
  {
    id: 'prod-25',
    distribuidoraId: 'dist-1',
    name: 'Manaos Cola 2.25L',
    category: 'Bebidas',
    price: 980,
    stock: 300,
    description: 'Gaseosa Manaos cola económica 2.25 litros',
    active: true,
  status: 'active',
    rating: 4.1,
    reviewCount: 58,
  },
  {
    id: 'prod-26',
    distribuidoraId: 'dist-1',
    name: 'Heineken Lata 473ml (x6)',
    category: 'Bebidas',
    price: 8400,
    stock: 55,
    description: 'Six pack Heineken lata 473ml',
    active: true,
  status: 'active',
    rating: 4.9,
    reviewCount: 114,
  },
  {
    id: 'prod-27',
    distribuidoraId: 'dist-1',
    name: 'Pepsi 2.25L',
    category: 'Bebidas',
    price: 1750,
    stock: 140,
    description: 'Gaseosa Pepsi botella 2.25 litros',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 77,
  },
  {
    id: 'prod-28',
    distribuidoraId: 'dist-1',
    name: 'Doritos Queso Cheddar 180g',
    category: 'Snacks',
    price: 2800,
    stock: 6,
    description: 'Chips Doritos sabor queso cheddar',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 49,
  },

  // ── Lácteos Frescos — productos adicionales ───────────────────────────────
  {
    id: 'prod-29',
    distribuidoraId: 'dist-2',
    name: 'Crema de Leche La Serenísima 200ml',
    category: 'Lácteos',
    price: 1650,
    stock: 95,
    description: 'Crema de leche entera La Serenísima',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 83,
  },
  {
    id: 'prod-30',
    distribuidoraId: 'dist-2',
    name: 'Ricota La Serenísima 400g',
    category: 'Lácteos',
    price: 2100,
    stock: 70,
    description: 'Ricota fresca La Serenísima 400g',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 61,
  },
  {
    id: 'prod-31',
    distribuidoraId: 'dist-2',
    name: 'Leche Chocolatada Cindor 1L',
    category: 'Lácteos',
    price: 1480,
    stock: 130,
    description: 'Leche saborizada chocolatada Cindor 1 litro',
    active: true,
  status: 'active',
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: 'prod-32',
    distribuidoraId: 'dist-2',
    name: 'Mozzarella Sancor 300g',
    category: 'Lácteos',
    price: 3800,
    stock: 50,
    description: 'Queso mozzarella Sancor feteado 300g',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 38,
  },
  {
    id: 'prod-33',
    distribuidoraId: 'dist-2',
    name: 'Salame Milán La Salamandra 250g',
    category: 'Fiambres',
    price: 4200,
    stock: 40,
    description: 'Salame de Milán curado La Salamandra',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 52,
  },
  {
    id: 'prod-34',
    distribuidoraId: 'dist-2',
    name: 'Mortadela Paladini 200g',
    category: 'Fiambres',
    price: 2600,
    stock: 65,
    description: 'Mortadela Paladini feteada 200g',
    active: true,
  status: 'active',
    rating: 4.4,
    reviewCount: 29,
  },
  {
    id: 'prod-35',
    distribuidoraId: 'dist-2',
    name: 'Leche Descremada La Serenísima 1L',
    category: 'Lácteos',
    price: 1300,
    stock: 8,
    description: 'Leche descremada La Serenísima sachet 1L',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 74,
  },
  {
    id: 'prod-36',
    distribuidoraId: 'dist-2',
    name: 'Dulce de Leche La Serenísima 400g',
    category: 'Lácteos',
    price: 2900,
    stock: 110,
    description: 'Dulce de leche repostero La Serenísima 400g',
    active: true,
  status: 'active',
    rating: 5.0,
    reviewCount: 203,
  },

  // ── Panaderos Unidos — productos adicionales ──────────────────────────────
  {
    id: 'prod-37',
    distribuidoraId: 'dist-3',
    name: 'Bizcochos de Grasa (docena)',
    category: 'Panadería',
    price: 1800,
    stock: 60,
    description: 'Bizcochos de grasa artesanales, docena',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: 'prod-38',
    distribuidoraId: 'dist-3',
    name: 'Pan de Molde Integral Bimbo 500g',
    category: 'Panadería',
    price: 1900,
    stock: 45,
    description: 'Pan lactal integral Bimbo 500g',
    active: true,
  status: 'active',
    rating: 4.5,
    reviewCount: 42,
  },
  {
    id: 'prod-39',
    distribuidoraId: 'dist-3',
    name: 'Galletas de Agua La Favorita x200g',
    category: 'Panadería',
    price: 1450,
    stock: 80,
    description: 'Galletas de agua crujientes La Favorita',
    active: true,
  status: 'active',
    rating: 4.3,
    reviewCount: 31,
  },
  {
    id: 'prod-40',
    distribuidoraId: 'dist-3',
    name: 'Tostadas Light 150g',
    category: 'Panadería',
    price: 1200,
    stock: 70,
    description: 'Tostadas light finas y crocantes',
    active: true,
  status: 'active',
    rating: 4.4,
    reviewCount: 27,
  },
  {
    id: 'prod-41',
    distribuidoraId: 'dist-3',
    name: 'Alfajores Cachafaz x6',
    category: 'Panadería',
    price: 6500,
    stock: 25,
    description: 'Alfajores de maicena Cachafaz, caja 6 unidades',
    active: true,
  status: 'active',
    rating: 5.0,
    reviewCount: 175,
  },
  {
    id: 'prod-42',
    distribuidoraId: 'dist-3',
    name: 'Masa Hojaldre 500g',
    category: 'Panadería',
    price: 2200,
    stock: 9,
    description: 'Masa de hojaldre lista para usar 500g',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 53,
  },
  {
    id: 'prod-43',
    distribuidoraId: 'dist-3',
    name: 'Tapas Empanadas x12',
    category: 'Panadería',
    price: 1600,
    stock: 55,
    description: 'Tapas de empanadas para horno, 12 unidades',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 109,
  },

  // ── Mega Distribuidora — productos adicionales ────────────────────────────
  {
    id: 'prod-44',
    distribuidoraId: 'dist-4',
    name: 'Yerba Mate Taragüí 1kg',
    category: 'Almacén',
    price: 3200,
    stock: 180,
    description: 'Yerba mate Taragüí sin palo 1 kilo',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 142,
  },
  {
    id: 'prod-45',
    distribuidoraId: 'dist-4',
    name: 'Harina 000 Tres Chorros 1kg',
    category: 'Almacén',
    price: 1100,
    stock: 250,
    description: 'Harina de trigo 000 para pan y pizza',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 88,
  },
  {
    id: 'prod-46',
    distribuidoraId: 'dist-4',
    name: 'Puré de Tomate Arcor 520ml',
    category: 'Almacén',
    price: 980,
    stock: 200,
    description: 'Puré de tomate Arcor tetra 520ml',
    active: true,
  status: 'active',
    rating: 4.5,
    reviewCount: 61,
  },
  {
    id: 'prod-47',
    distribuidoraId: 'dist-4',
    name: 'Sal Fina Celusal 1kg',
    category: 'Almacén',
    price: 650,
    stock: 300,
    description: 'Sal fina Celusal bolsa 1 kilo',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 55,
  },
  {
    id: 'prod-48',
    distribuidoraId: 'dist-4',
    name: 'Jabón en Polvo Ariel 1kg',
    category: 'Limpieza',
    price: 4500,
    stock: 75,
    description: 'Jabón en polvo Ariel multiacción 1 kilo',
    active: true,
  status: 'active',
    rating: 4.8,
    reviewCount: 97,
  },
  {
    id: 'prod-49',
    distribuidoraId: 'dist-4',
    name: 'Papel Higiénico Elite x4',
    category: 'Limpieza',
    price: 2800,
    stock: 110,
    description: 'Papel higiénico Elite doble hoja, pack 4 rollos',
    active: true,
  status: 'active',
    rating: 4.6,
    reviewCount: 73,
  },
  {
    id: 'prod-50',
    distribuidoraId: 'dist-4',
    name: 'Lentil Gallo Oro 500g',
    category: 'Almacén',
    price: 1200,
    stock: 160,
    description: 'Lentejas Gallo Oro bolsa 500g',
    active: true,
  status: 'active',
    rating: 4.4,
    reviewCount: 34,
  },
  {
    id: 'prod-51',
    distribuidoraId: 'dist-4',
    name: 'Aceite de Oliva Cocinero 500ml',
    category: 'Almacén',
    price: 5800,
    stock: 60,
    description: 'Aceite de oliva extra virgen Cocinero 500ml',
    active: true,
  status: 'active',
    rating: 4.7,
    reviewCount: 82,
  },
  {
    id: 'prod-52',
    distribuidoraId: 'dist-4',
    name: 'Suavizante Comfort 3L',
    category: 'Limpieza',
    price: 3200,
    stock: 5,
    description: 'Suavizante de ropa Comfort floral 3 litros',
    active: true,
  status: 'active',
    rating: 4.5,
    reviewCount: 46,
  },
]

// Mock orders
export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'STK-2024-001',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-1',
    distribuidoraName: 'Bebidas del Sur',
    items: [
      { productId: 'prod-1', productName: 'Coca-Cola 2.25L', quantity: 24, unitPrice: 1850 },
      { productId: 'prod-2', productName: 'Sprite 2.25L', quantity: 12, unitPrice: 1750 },
      { productId: 'prod-3', productName: 'Agua Mineral Villavicencio 1.5L', quantity: 36, unitPrice: 980 },
    ],
    subtotal: 100680,
    total: 100680,
    status: 'entregado',
    createdAt: '2024-03-10T14:30:00',
    updatedAt: '2024-03-11T10:00:00',
    zone: 'Centro',
  },
  {
    id: 'order-2',
    orderNumber: 'STK-2024-002',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-2',
    distribuidoraName: 'Lácteos Frescos SRL',
    items: [
      { productId: 'prod-6', productName: 'Leche La Serenísima 1L', quantity: 48, unitPrice: 1250 },
      { productId: 'prod-8', productName: 'Queso Cremoso Tregar 1kg', quantity: 5, unitPrice: 8500 },
    ],
    subtotal: 102500,
    total: 102500,
    status: 'en_preparacion',
    createdAt: '2024-03-12T09:15:00',
    updatedAt: '2024-03-12T11:30:00',
    zone: 'Centro',
  },
  {
    id: 'order-3',
    orderNumber: 'STK-2024-003',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-3',
    distribuidoraName: 'Panaderos Unidos',
    items: [
      { productId: 'prod-11', productName: 'Pan Francés (docena)', quantity: 10, unitPrice: 1200 },
      { productId: 'prod-12', productName: 'Medialunas (docena)', quantity: 5, unitPrice: 2800 },
    ],
    subtotal: 26000,
    total: 26000,
    status: 'pagado',
    createdAt: '2024-03-12T08:00:00',
    updatedAt: '2024-03-12T08:30:00',
    zone: 'Este',
  },
  {
    id: 'order-4',
    orderNumber: 'STK-2024-004',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-4',
    distribuidoraName: 'Mega Distribuidora',
    items: [
      { productId: 'prod-15', productName: 'Arroz Gallo Oro 1kg', quantity: 20, unitPrice: 1450 },
      { productId: 'prod-16', productName: 'Fideos Matarazzo 500g', quantity: 30, unitPrice: 980 },
      { productId: 'prod-19', productName: 'Aceite Cocinero 1.5L', quantity: 12, unitPrice: 2200 },
    ],
    subtotal: 84800,
    total: 84800,
    status: 'pendiente',
    createdAt: '2024-03-12T16:45:00',
    updatedAt: '2024-03-12T16:45:00',
    zone: 'Centro',
  },

  // ── Pedidos adicionales Bebidas del Sur (dist-1) ──────────────────────────
  {
    id: 'order-5',
    orderNumber: 'STK-2024-005',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-1',
    distribuidoraName: 'Bebidas del Sur',
    items: [
      { productId: 'prod-1', productName: 'Coca-Cola 2.25L', quantity: 48, unitPrice: 1850 },
      { productId: 'prod-4', productName: 'Cerveza Quilmes 1L', quantity: 24, unitPrice: 2100 },
    ],
    subtotal: 138600,
    total: 138600,
    status: 'pagado',
    createdAt: '2024-03-13T10:00:00',
    updatedAt: '2024-03-13T10:30:00',
    zone: 'Centro',
  },
  {
    id: 'order-6',
    orderNumber: 'STK-2024-006',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-1',
    distribuidoraName: 'Bebidas del Sur',
    items: [
      { productId: 'prod-2', productName: 'Sprite 2.25L', quantity: 24, unitPrice: 1750 },
      { productId: 'prod-23', productName: 'Jugo Cepita Naranja 1L (x12)', quantity: 2, unitPrice: 14400 },
    ],
    subtotal: 70800,
    total: 70800,
    status: 'entregado',
    createdAt: '2024-03-11T14:00:00',
    updatedAt: '2024-03-12T09:00:00',
    zone: 'Este',
  },
  {
    id: 'order-7',
    orderNumber: 'STK-2024-007',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-1',
    distribuidoraName: 'Bebidas del Sur',
    items: [
      { productId: 'prod-3', productName: 'Agua Mineral Villavicencio 1.5L', quantity: 48, unitPrice: 980 },
      { productId: 'prod-26', productName: 'Heineken Lata 473ml (x6)', quantity: 10, unitPrice: 8400 },
      { productId: 'prod-5', productName: 'Papas Lays Clásicas 270g', quantity: 20, unitPrice: 2450 },
    ],
    subtotal: 179040,
    total: 179040,
    status: 'en_preparacion',
    createdAt: '2024-03-14T08:30:00',
    updatedAt: '2024-03-14T09:15:00',
    zone: 'Centro',
  },
  {
    id: 'order-8',
    orderNumber: 'STK-2024-008',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-1',
    distribuidoraName: 'Bebidas del Sur',
    items: [
      { productId: 'prod-25', productName: 'Manaos Cola 2.25L', quantity: 36, unitPrice: 980 },
      { productId: 'prod-22', productName: 'Gatorade Naranja 500ml', quantity: 24, unitPrice: 1350 },
    ],
    subtotal: 67680,
    total: 67680,
    status: 'pendiente',
    createdAt: '2024-03-14T16:00:00',
    updatedAt: '2024-03-14T16:00:00',
    zone: 'Este',
  },

  // ── Pedidos adicionales Lácteos Frescos (dist-2) ──────────────────────────
  {
    id: 'order-9',
    orderNumber: 'STK-2024-009',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-2',
    distribuidoraName: 'Lácteos Frescos SRL',
    items: [
      { productId: 'prod-6', productName: 'Leche La Serenísima 1L', quantity: 60, unitPrice: 1250 },
      { productId: 'prod-36', productName: 'Dulce de Leche La Serenísima 400g', quantity: 12, unitPrice: 2900 },
      { productId: 'prod-29', productName: 'Crema de Leche La Serenísima 200ml', quantity: 24, unitPrice: 1650 },
    ],
    subtotal: 149100,
    total: 149100,
    status: 'entregado',
    createdAt: '2024-03-09T07:30:00',
    updatedAt: '2024-03-09T12:00:00',
    zone: 'Centro',
  },
  {
    id: 'order-10',
    orderNumber: 'STK-2024-010',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-2',
    distribuidoraName: 'Lácteos Frescos SRL',
    items: [
      { productId: 'prod-31', productName: 'Leche Chocolatada Cindor 1L', quantity: 36, unitPrice: 1480 },
      { productId: 'prod-7', productName: 'Yogur Activia Natural 190g', quantity: 24, unitPrice: 890 },
    ],
    subtotal: 74640,
    total: 74640,
    status: 'pagado',
    createdAt: '2024-03-13T08:00:00',
    updatedAt: '2024-03-13T08:45:00',
    zone: 'Este',
  },
  {
    id: 'order-11',
    orderNumber: 'STK-2024-011',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-2',
    distribuidoraName: 'Lácteos Frescos SRL',
    items: [
      { productId: 'prod-9', productName: 'Jamón Cocido Paladini 200g', quantity: 20, unitPrice: 3200 },
      { productId: 'prod-33', productName: 'Salame Milán La Salamandra 250g', quantity: 10, unitPrice: 4200 },
      { productId: 'prod-32', productName: 'Mozzarella Sancor 300g', quantity: 15, unitPrice: 3800 },
    ],
    subtotal: 163000,
    total: 163000,
    status: 'pendiente',
    createdAt: '2024-03-14T14:20:00',
    updatedAt: '2024-03-14T14:20:00',
    zone: 'Centro',
  },
  {
    id: 'order-12',
    orderNumber: 'STK-2024-012',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-2',
    distribuidoraName: 'Lácteos Frescos SRL',
    items: [
      { productId: 'prod-10', productName: 'Manteca La Serenísima 200g', quantity: 30, unitPrice: 2100 },
      { productId: 'prod-8', productName: 'Queso Cremoso Tregar 1kg', quantity: 3, unitPrice: 8500 },
    ],
    subtotal: 88500,
    total: 88500,
    status: 'en_preparacion',
    createdAt: '2024-03-14T10:00:00',
    updatedAt: '2024-03-14T11:30:00',
    zone: 'Este',
  },

  // ── Pedidos adicionales Panaderos Unidos (dist-3) ─────────────────────────
  {
    id: 'order-13',
    orderNumber: 'STK-2024-013',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-3',
    distribuidoraName: 'Panaderos Unidos',
    items: [
      { productId: 'prod-11', productName: 'Pan Francés (docena)', quantity: 20, unitPrice: 1200 },
      { productId: 'prod-41', productName: 'Alfajores Cachafaz x6', quantity: 5, unitPrice: 6500 },
      { productId: 'prod-37', productName: 'Bizcochos de Grasa (docena)', quantity: 10, unitPrice: 1800 },
    ],
    subtotal: 74500,
    total: 74500,
    status: 'entregado',
    createdAt: '2024-03-10T06:00:00',
    updatedAt: '2024-03-10T08:30:00',
    zone: 'Centro',
  },
  {
    id: 'order-14',
    orderNumber: 'STK-2024-014',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-3',
    distribuidoraName: 'Panaderos Unidos',
    items: [
      { productId: 'prod-14', productName: 'Facturas Surtidas (docena)', quantity: 8, unitPrice: 3500 },
      { productId: 'prod-43', productName: 'Tapas Empanadas x12', quantity: 10, unitPrice: 1600 },
    ],
    subtotal: 44000,
    total: 44000,
    status: 'pagado',
    createdAt: '2024-03-13T06:30:00',
    updatedAt: '2024-03-13T07:00:00',
    zone: 'Este',
  },
  {
    id: 'order-15',
    orderNumber: 'STK-2024-015',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-3',
    distribuidoraName: 'Panaderos Unidos',
    items: [
      { productId: 'prod-12', productName: 'Medialunas (docena)', quantity: 15, unitPrice: 2800 },
      { productId: 'prod-38', productName: 'Pan de Molde Integral Bimbo 500g', quantity: 20, unitPrice: 1900 },
    ],
    subtotal: 80000,
    total: 80000,
    status: 'en_preparacion',
    createdAt: '2024-03-14T05:45:00',
    updatedAt: '2024-03-14T06:30:00',
    zone: 'Centro',
  },
  {
    id: 'order-16',
    orderNumber: 'STK-2024-016',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-3',
    distribuidoraName: 'Panaderos Unidos',
    items: [
      { productId: 'prod-13', productName: 'Pan Lactal Bimbo 500g', quantity: 30, unitPrice: 1650 },
      { productId: 'prod-39', productName: 'Galletas de Agua La Favorita x200g', quantity: 20, unitPrice: 1450 },
    ],
    subtotal: 78500,
    total: 78500,
    status: 'pendiente',
    createdAt: '2024-03-14T15:00:00',
    updatedAt: '2024-03-14T15:00:00',
    zone: 'Este',
  },

  // ── Pedidos adicionales Mega Distribuidora (dist-4) ───────────────────────
  {
    id: 'order-17',
    orderNumber: 'STK-2024-017',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-4',
    distribuidoraName: 'Mega Distribuidora',
    items: [
      { productId: 'prod-44', productName: 'Yerba Mate Taragüí 1kg', quantity: 15, unitPrice: 3200 },
      { productId: 'prod-48', productName: 'Jabón en Polvo Ariel 1kg', quantity: 10, unitPrice: 4500 },
      { productId: 'prod-46', productName: 'Puré de Tomate Arcor 520ml', quantity: 24, unitPrice: 980 },
    ],
    subtotal: 117720,
    total: 117720,
    status: 'entregado',
    createdAt: '2024-03-08T09:00:00',
    updatedAt: '2024-03-09T14:00:00',
    zone: 'Este',
  },
  {
    id: 'order-18',
    orderNumber: 'STK-2024-018',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-4',
    distribuidoraName: 'Mega Distribuidora',
    items: [
      { productId: 'prod-17', productName: 'Lavandina Ayudín 2L', quantity: 24, unitPrice: 1100 },
      { productId: 'prod-49', productName: 'Papel Higiénico Elite x4', quantity: 30, unitPrice: 2800 },
      { productId: 'prod-18', productName: 'Detergente Magistral 750ml', quantity: 20, unitPrice: 1850 },
    ],
    subtotal: 153800,
    total: 153800,
    status: 'pagado',
    createdAt: '2024-03-13T11:00:00',
    updatedAt: '2024-03-13T11:30:00',
    zone: 'Centro',
  },
  {
    id: 'order-19',
    orderNumber: 'STK-2024-019',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-4',
    distribuidoraName: 'Mega Distribuidora',
    items: [
      { productId: 'prod-20', productName: 'Azúcar Ledesma 1kg', quantity: 30, unitPrice: 1050 },
      { productId: 'prod-45', productName: 'Harina 000 Tres Chorros 1kg', quantity: 20, unitPrice: 1100 },
      { productId: 'prod-51', productName: 'Aceite de Oliva Cocinero 500ml', quantity: 6, unitPrice: 5800 },
    ],
    subtotal: 88300,
    total: 88300,
    status: 'en_preparacion',
    createdAt: '2024-03-14T12:00:00',
    updatedAt: '2024-03-14T13:00:00',
    zone: 'Este',
  },
  {
    id: 'order-20',
    orderNumber: 'STK-2024-020',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-4',
    distribuidoraName: 'Mega Distribuidora',
    items: [
      { productId: 'prod-15', productName: 'Arroz Gallo Oro 1kg', quantity: 40, unitPrice: 1450 },
      { productId: 'prod-47', productName: 'Sal Fina Celusal 1kg', quantity: 50, unitPrice: 650 },
      { productId: 'prod-50', productName: 'Lentil Gallo Oro 500g', quantity: 30, unitPrice: 1200 },
    ],
    subtotal: 126500,
    total: 126500,
    status: 'pendiente',
    createdAt: '2024-03-14T17:30:00',
    updatedAt: '2024-03-14T17:30:00',
    zone: 'Centro',
  },
  // ── External-payment orders (Coordinar con distribuidora) ──────────────────
  {
    id: 'order-ext-1',
    orderNumber: 'STK-2024-EXT-001',
    comercioId: 'com-1',
    comercioName: 'Almacén Don Pedro',
    distribuidoraId: 'dist-1',
    distribuidoraName: 'Bebidas del Sur',
    items: [
      { productId: 'prod-1', productName: 'Coca-Cola 2.25L', quantity: 48, unitPrice: 1850 },
      { productId: 'prod-4', productName: 'Cerveza Quilmes 1L', quantity: 24, unitPrice: 2100 },
    ],
    subtotal: 139200,
    total: 139200,
    status: 'pendiente',
    createdAt: '2024-11-14T10:00:00Z',
    updatedAt: '2024-11-14T10:00:00Z',
    zone: 'Centro',
    paymentMethod: 'external',
    firestoreStatus: 'pending_confirmation',
    commissionGenerated: false,
  },
  {
    id: 'order-ext-2',
    orderNumber: 'STK-2024-EXT-002',
    comercioId: 'com-2',
    comercioName: 'Kiosco María',
    distribuidoraId: 'dist-1',
    distribuidoraName: 'Bebidas del Sur',
    items: [
      { productId: 'prod-2', productName: 'Sprite 2.25L', quantity: 24, unitPrice: 1750 },
      { productId: 'prod-5', productName: 'Papas Lays Clásicas 270g', quantity: 12, unitPrice: 2450 },
    ],
    subtotal: 71400,
    total: 71400,
    status: 'pagado',
    createdAt: '2024-11-12T09:30:00Z',
    updatedAt: '2024-11-12T14:00:00Z',
    zone: 'Este',
    paymentMethod: 'external',
    firestoreStatus: 'confirmed',
    commissionGenerated: false,
  },
  {
    id: 'order-ext-3',
    orderNumber: 'STK-2024-EXT-003',
    comercioId: 'com-3',
    comercioName: 'Mini Market El Sol',
    distribuidoraId: 'dist-1',
    distribuidoraName: 'Bebidas del Sur',
    items: [
      { productId: 'prod-1', productName: 'Coca-Cola 2.25L', quantity: 24, unitPrice: 1850 },
    ],
    subtotal: 44400,
    total: 44400,
    status: 'pendiente',
    createdAt: '2024-11-10T16:00:00Z',
    updatedAt: '2024-11-11T10:00:00Z',
    zone: 'Norte',
    paymentMethod: 'external',
    firestoreStatus: 'cancelled',
    cancellationReason: 'Falta de stock',
    commissionGenerated: false,
  },
]

// Dashboard KPIs for distribuidora
export const mockDashboardKPIs: DashboardKPIs = {
  ventasHoy: 187500,
  pedidosHoy: 8,
  pendientes: 3,
  stockOk: 94,
}

// Helper functions
export function getProductsByDistribuidora(distribuidoraId: string): Product[] {
  return mockProducts.filter(p => p.distribuidoraId === distribuidoraId)
}

export function getOrdersByComercio(comercioId: string): Order[] {
  return mockOrders.filter(o => o.comercioId === comercioId)
}

export function getOrdersByDistribuidora(distribuidoraId: string): Order[] {
  return mockOrders.filter(o => o.distribuidoraId === distribuidoraId)
}

export function getDistribuidoraById(id: string): Distribuidora | undefined {
  return mockDistribuidoras.find(d => d.id === id)
}

export function getLowStockProducts(distribuidoraId: string, threshold = 10): Product[] {
  return mockProducts.filter(p => p.distribuidoraId === distribuidoraId && p.stock > 0 && p.stock <= threshold)
}

export function getEstimatedDeliveryDate(deliveryTimeHours: number): string {
  const date = new Date()
  let hoursLeft = deliveryTimeHours
  while (hoursLeft > 0) {
    date.setHours(date.getHours() + 1)
    const day = date.getDay()   // 0=Sun, 6=Sat
    const hour = date.getHours()
    if (day !== 0 && day !== 6 && hour >= 8 && hour < 18) {
      hoursLeft--
    }
  }
  return date.toLocaleDateString('es-AR', { weekday: 'long', day: 'numeric', month: 'long' })
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('es-AR', {
    style: 'currency',
    currency: 'ARS',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

export function getStatusLabel(status: string): string {
  const labels: Record<string, string> = {
    pendiente: 'Pendiente',
    pagado: 'Pagado',
    en_preparacion: 'En preparación',
    entregado: 'Entregado',
  }
  return labels[status] || status
}

export function getStatusColor(status: string): string {
  const colors: Record<string, string> = {
    pendiente: 'bg-warning/10 text-warning',
    pagado: 'bg-info/10 text-info',
    en_preparacion: 'bg-primary/10 text-primary',
    entregado: 'bg-success/10 text-success',
  }
  return colors[status] || 'bg-muted text-muted-foreground'
}
